"""Public compatibility facade for SPA capture modules."""

from __future__ import annotations

from crawler.spa.capture_core import (
    build_api_base_key,
    build_api_candidate_key,
    build_api_cluster_key,
    build_synthesized_html,
    collect_routes_from_page,
    enqueue_routes,
    extract_dom_links,
    generate_api_hash,
    intercept_request,
    intercept_response,
    is_in_scope,
    normalize_url,
    record_api_candidate,
    route_priority,
    should_collect_url,
)
from crawler.spa.capture_core import (
    INTROSPECTION_QUERY,
    MAX_GRAPHQL_SCHEMAS,
    MAX_ID_SAMPLES_PER_PATTERN,
    MAX_PAYLOAD_SIZE,
    MAX_SYNTHESIZED_APIS,
    MAX_SYNTHESIZED_LINKS,
    MAX_URL_CACHE_SIZE,
    _CAPTURE_SOURCES,
    _MUTATING_METHODS,
)
from crawler.spa.capture_enrichment import (
    best_source_url_for_path as _best_source_url_for_path,
    canonical_api_path as _canonical_api_path,
    collect_global_response_metadata,
    enrich_api_endpoints_from_observations,
    enrich_source_urls,
    fallback_content_type_for_api as _fallback_content_type_for_api,
    fallback_server_info_for_api as _fallback_server_info_for_api,
    hydrate_fields_from_source_context as _hydrate_fields_from_source_context,
    infer_companion_action_endpoints,
    normalize_mutating_path_endpoints,
    path_has_mutating_with_body as _path_has_mutating_with_body,
    prioritize_api_endpoints,
    probe_endpoint_methods_precise,
    representative_url_for_path as _representative_url_for_path,
    score_api_endpoint as _score_api_endpoint,
)
from crawler.spa.capture_graphql import (
    build_graphql_forms_from_captures,
    extract_graphql_schema,
    graphql_endpoint_key,
    record_graphql_capture,
    unwrap_graphql_type,
)

__all__ = [
    "INTROSPECTION_QUERY",
    "MAX_GRAPHQL_SCHEMAS",
    "MAX_ID_SAMPLES_PER_PATTERN",
    "MAX_PAYLOAD_SIZE",
    "MAX_SYNTHESIZED_APIS",
    "MAX_SYNTHESIZED_LINKS",
    "MAX_URL_CACHE_SIZE",
    "_CAPTURE_SOURCES",
    "_MUTATING_METHODS",
    "build_api_base_key",
    "build_api_candidate_key",
    "build_api_cluster_key",
    "build_graphql_forms_from_captures",
    "build_synthesized_html",
    "collect_global_response_metadata",
    "collect_routes_from_page",
    "enqueue_routes",
    "enrich_api_endpoints_from_observations",
    "enrich_source_urls",
    "extract_dom_links",
    "extract_graphql_schema",
    "generate_api_hash",
    "graphql_endpoint_key",
    "infer_companion_action_endpoints",
    "intercept_request",
    "intercept_response",
    "is_in_scope",
    "normalize_mutating_path_endpoints",
    "normalize_url",
    "prioritize_api_endpoints",
    "probe_endpoint_methods_precise",
    "record_api_candidate",
    "record_graphql_capture",
    "route_priority",
    "should_collect_url",
    "unwrap_graphql_type",
]
